build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"

args:
  BUILD_ARCH: "{arch}"
  BUILD_DATE: "{build_date}"
  BUILD_DESCRIPTION: "Model Context Protocol server for Home Assistant historical data"
  BUILD_NAME: "MCP Server"
  BUILD_REF: "{build_ref}"
  BUILD_REPOSITORY: "https://github.com/mar-eid/ha-addon-mcp"
  BUILD_VERSION: "{version}"

labels:
  org.opencontainers.image.title: "MCP Server"
  org.opencontainers.image.description: "Model Context Protocol server for Home Assistant historical data"
  org.opencontainers.image.source: "https://github.com/mar-eid/ha-addon-mcp"
  org.opencontainers.image.licenses: "MIT"