{
  "name": "MCP Server",
  "version": "0.1.2",
  "slug": "mcp_server",
  "description": "MCP-server som henter historikk/statistikk fra Home Assistant/Recorder.",
  "arch": ["amd64", "aarch64"],
  "startup": "services",
  "boot": "auto",
  "ingress": true,
  "ingress_port": 0,
  "panel_icon": "mdi:database",
  "homeassistant": "2024.0.0",
  "image": "ghcr.io/mar-eid/ha-addon-mcp-{arch}",
  "ports": {},
  "options": {
    "pg_host": "127.0.0.1",
    "pg_port": 5432,
    "pg_database": "homeassistant",
    "pg_user": "ha_read",
    "pg_password": "",
    "read_only": true,
    "enable_timescaledb": false
  },
  "schema": {
    "pg_host": "str",
    "pg_port": "int",
    "pg_database": "str",
    "pg_user": "str",
    "pg_password": "str?",
    "read_only": "bool",
    "enable_timescaledb": "bool"
  }
}