name: Build & Push MCP Add-on

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

# Global permissions for the entire workflow
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Job-level permissions (redundant but explicit)
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            ha_arch: amd64
          - platform: linux/arm64
            ha_arch: aarch64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read addon version from config
        id: version
        run: |
          # Install yq for YAML parsing
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          
          # Read version from config.yaml
          VERSION=$(yq eval '.version' mcp-server/config.yaml)
          echo "ADDON_VERSION=$VERSION" >> $GITHUB_ENV
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "📦 Building version: $VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr  
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ env.ADDON_VERSION }}
            type=sha,prefix={{date 'YYYYMMDD'}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./mcp-server
          platforms: ${{ matrix.platform }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.ha_arch }}-base:3.19
            BUILD_ARCH=${{ matrix.ha_arch }}
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_DESCRIPTION=MCP server for Home Assistant historical data
            BUILD_NAME=MCP Server
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.server_url }}/${{ github.repository }}
            BUILD_VERSION=${{ env.ADDON_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Verify published image
        run: |
          echo "✅ Published images:"
          echo "ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}:latest"
          echo "ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}:${{ env.ADDON_VERSION }}"