name: Build & Push MCP Add-on

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: ["amd64", "aarch64"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read addon version
        id: version
        run: |
          VERSION=$(yq eval '.version' mcp-server/config.yaml)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Using version: ${VERSION}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.arch }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=raw,value=latest,enable={{is_default_branch}}
            type=raw,value=${{ steps.version.outputs.version }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./mcp-server
          platforms: linux/${{ matrix.arch == 'aarch64' && 'arm64' || matrix.arch }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:3.19
            BUILD_ARCH=${{ matrix.arch }}
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            BUILD_DESCRIPTION=MCP server for Home Assistant historical data
            BUILD_NAME=MCP Server
            BUILD_REF=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.revision'] }}
            BUILD_REPOSITORY=${{ github.server_url }}/${{ github.repository }}
            BUILD_VERSION=${{ steps.version.outputs.version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  repository:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update repository.json
        run: |
          cat > repository.json << EOF
          {
            "name": "MCP Add-ons by mar-eid", 
            "url": "https://github.com/${{ github.repository }}",
            "maintainer": "${{ github.repository_owner }}"
          }
          EOF

      - name: Commit repository.json
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add repository.json
          git diff --staged --quiet || git commit -m "Auto-update repository.json"
          git push