name: Build & Push MCP Add-on

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            ha_arch: amd64
          - platform: linux/arm64
            ha_arch: aarch64
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./mcp-server
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}:latest
            ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}:${{ github.sha }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.ha_arch }}-base:3.19
