name: Build & Push MCP Add-on

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        include:
          - platform: linux/amd64
            ha_arch: amd64
          - platform: linux/arm64
            ha_arch: aarch64

    steps:
      - uses: actions/checkout@v4

      - name: Read addon version from config
        id: ver
        run: |
          # Check if config.yaml exists, otherwise use config.json
          if [[ -f "mcp-server/config.yaml" ]]; then
            # Install yq if needed
            sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
            sudo chmod +x /usr/local/bin/yq
            VERSION=$(yq eval '.version' mcp-server/config.yaml)
          else
            VERSION=$(jq -r .version mcp-server/config.json)
          fi
          echo "ADDON_VERSION=$VERSION" >> $GITHUB_ENV
          echo "Using version: $VERSION"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: ./mcp-server
          platforms: ${{ matrix.platform }}
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}:latest
            ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}:${{ env.ADDON_VERSION }}
            ghcr.io/${{ github.repository_owner }}/ha-addon-mcp-${{ matrix.ha_arch }}:${{ github.sha }}
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.ha_arch }}-base:3.19
            BUILD_ARCH=${{ matrix.ha_arch }}
            BUILD_DATE=${{ github.event.head_commit.timestamp }}
            BUILD_DESCRIPTION=MCP server for Home Assistant historical data
            BUILD_NAME=MCP Server
            BUILD_REF=${{ github.sha }}
            BUILD_REPOSITORY=${{ github.server_url }}/${{ github.repository }}
            BUILD_VERSION=${{ env.ADDON_VERSION }}